method: bayes
metric:
  goal: minimize
  name: val_loss
name: sweep CI3P ATT BH
program: ./w_and_b/ATT_BH/train.py
parameters:
  batch_size:
    values:
      - 512
      - 1024
      - 2048
      - 4096
  embed_dim:
    values:
      - 128
      - 256
      - 512
  lr:
    distribution: uniform
    max: 0.0001
    min: 1e-05
  n_heads:
    values:
      - 4
      - 8
      - 16