#num_steps: 3000000
#batch_size: 128
#lr: 0.00005
#memory_size: 10000
#gamma: 0.99
#multi_step: 1
#target_entropy_ratio: 0.1
#start_steps: 10000
#update_interval: 4
#target_update_interval: 3000
#use_per: True
#dueling_net: True
#num_eval_steps: 3000
#max_episode_steps: 600
#log_interval: 10
#eval_interval: 10000
#save_interval: 100000

name: "sacd_new_reward_more_updates"
num_steps: 6000000
batch_size: 512
lr: 0.0001
memory_size: 100000
gamma: 0.99
multi_step: 10
target_entropy_ratio: 0.2
start_steps: 50000
update_interval: 4
target_update_interval: 1000
use_per: True
dueling_net: True
num_eval_steps: 300000
max_episode_steps: 500
log_interval: 1
eval_interval: 5000 # units: epsisodes
save_interval: 100000
max_grad_norm: 5