#num_steps: 3000000
#batch_size: 128
#lr: 0.00005
#memory_size: 10000
#gamma: 0.99
#multi_step: 1
#target_entropy_ratio: 0.1
#start_steps: 10000
#update_interval: 4
#target_update_interval: 3000
#use_per: True
#dueling_net: True
#num_eval_steps: 3000
#max_episode_steps: 600
#log_interval: 10
#eval_interval: 10000
#save_interval: 100000

name: "hyreal_a2c_reward"
lr: 0.00005
gamma: 0.99
multi_step: 1
max_grad_norm: 100.0
value_coeff: 0.5
entropy_coef: 0.00
num_eval_steps: 300000
max_episode_steps: 500
max_episodes: 10000
log_interval: 100
eval_interval: 250 # units: epsisodes
save_interval: 100000
#eval_num_steps: 3000000